import numpy as np 
import matplotlib.pyplot as plt

len = 1000
A = np.array([2,4])
B = np.array([4,2])
C = np.array([-8,-6])
D = np.array([-5,2.5])
N = np.array([3,2]) 
L = np.zeros((2,len))
M = np.zeros((2,len))
N = np.zeros((2,len))
O = np.zeros((2,len))
P = np.zeros((2,len))
x = np.linspace(-10,10,len)
y = np.linspace(0,1,len)
for i in range(len):
	L[:,i] = C + y[i]*(B-C)
	M[:,i] = D + y[i]*(B-D)
	N[:,i] = D + y[i]*(A-D)
	O[:,i] = D + y[i]*(C-D)
	P[:,i] = C + y[i]*(A-C)

#plt.plot(L[0,:],L[1,:],'--g',label='image')
plt.plot(M[0,:],M[1,:])
plt.plot(N[0,:],N[1,:])
#plt.plot(O[0,:],O[1,:])
#plt.plot(P[0,:],P[1,:],label='minimum length')
plt.plot(A[0],A[1],'ro')
plt.plot(B[0],B[1],'ro')
plt.text(A[0]+1,A[1], 'B(2,4)')
plt.text(B[0]+1,B[1], 'A(4,2)')
#plt.text(C[0]+1,C[1], '$A^\prime(-8,-6)$')
#plt.plot(C[0],C[1],'ro')
plt.plot(D[0],D[1],'ro')
plt.plot(x,-(3*x+10)/2,label='$3x+4y+10=0$')
plt.axis('equal')
#plt.xlim(-20, 20)
#plt.ylim(-40, 20)
plt.grid()
plt.legend(loc='best')
plt.show()
